
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FairyTales.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class AspNetUser
{

    public AspNetUser()
    {

        this.AspNetUserClaims = new HashSet<AspNetUserClaim>();

        this.AspNetUserLogins = new HashSet<AspNetUserLogin>();

        this.User_Tale = new HashSet<User_Tale>();

        this.AspNetRoles = new HashSet<AspNetRole>();

    }


    public string Id { get; set; }

    public string UserName { get; set; }

    public string PasswordHash { get; set; }

    public string SecurityStamp { get; set; }

    public string FirstName { get; set; }

    public string SecondName { get; set; }

    public string Discriminator { get; set; }



    public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }

    public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }

    public virtual ICollection<User_Tale> User_Tale { get; set; }

    public virtual ICollection<AspNetRole> AspNetRoles { get; set; }

}

}
