
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FairyTales.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Author
{

    public Author()
    {

        this.Tales = new HashSet<Tale>();

    }


    public int Author_ID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }



    public virtual ICollection<Tale> Tales { get; set; }

}

}
