
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FairyTales.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class C__MigrationHistory
{

    public string MigrationId { get; set; }

    public string ContextKey { get; set; }

    public byte[] Model { get; set; }

    public string ProductVersion { get; set; }

}

}
