

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FairyTales.Entities
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DBFairytaleEntities : DbContext
{
    public DBFairytaleEntities()
        : base("name=DBFairytaleEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<Author> Authors { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

    public virtual DbSet<Tag> Tags { get; set; }

    public virtual DbSet<Tale> Tales { get; set; }

    public virtual DbSet<Tale_Tag> Tale_Tag { get; set; }

    public virtual DbSet<Type> Types { get; set; }

    public virtual DbSet<User_Tale> User_Tale { get; set; }

}

}

