
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FairyTales.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Tag
{

    public Tag()
    {

        this.Tale_Tag = new HashSet<Tale_Tag>();

    }


    public int Tag_ID { get; set; }

    public string Name { get; set; }



    public virtual ICollection<Tale_Tag> Tale_Tag { get; set; }

}

}
