//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairyTales.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tale_Tag
    {
        public int Tale_Tag_ID { get; set; }
        public int Tale_ID { get; set; }
        public int Tag_ID { get; set; }
    
        public virtual Tag Tag { get; set; }
        public virtual Tale Tale { get; set; }
    }
}
