
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FairyTales.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Tale_Tag
{

    public int Tale_Tag_ID { get; set; }

    public int Tale_ID { get; set; }

    public int Tag_ID { get; set; }



    public virtual Tag Tag { get; set; }

    public virtual Tale Tale { get; set; }

}

}
